services:
    postgres:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=pedro
            - POSTGRES_DB=stocks
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 80s

    api-server:
        restart: on-failure
        build: ./api_server
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - NODE_ENV=production

volumes:
    postgres_data:
